src/Entity/Card.php
<?php

namespace App\Entity;

use App\Repository\CardRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CardRepository::class)
 */
class Card
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $question;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $answer;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $tense;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $mood;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $sentence1;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $sentence2;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $image;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="card_author")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\ManyToOne(targetEntity=Category::class, inversedBy="cards")
     * @ORM\JoinColumn(nullable=false)
     */
    private $category;

    /**
     * @ORM\ManyToMany(targetEntity=Deck::class, inversedBy="cards")
     */
    private $decks;

    public function __construct()
    {
        $this->decks = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuestion(): ?string
    {
        return $this->question;
    }

    public function setQuestion(string $question): self
    {
        $this->question = $question;

        return $this;
    }

    public function getAnswer(): ?string
    {
        return $this->answer;
    }

    public function setAnswer(string $answer): self
    {
        $this->answer = $answer;

        return $this;
    }

    public function getTense(): ?string
    {
        return $this->tense;
    }

    public function setTense(?string $tense): self
    {
        $this->tense = $tense;

        return $this;
    }

    public function getMood(): ?string
    {
        return $this->mood;
    }

    public function setMood(?string $mood): self
    {
        $this->mood = $mood;

        return $this;
    }

    public function getSentence1(): ?string
    {
        return $this->sentence1;
    }

    public function setSentence1(?string $sentence1): self
    {
        $this->sentence1 = $sentence1;

        return $this;
    }

    public function getSentence2(): ?string
    {
        return $this->sentence2;
    }

    public function setSentence2(?string $sentence2): self
    {
        $this->sentence2 = $sentence2;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(?\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?category
    {
        return $this->category;
    }

    public function setCategory(?category $category): self
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection|deck[]
     */
    public function getDecks(): Collection
    {
        return $this->decks;
    }

    public function addDeck(deck $deck): self
    {
        if (!$this->decks->contains($deck)) {
            $this->decks[] = $deck;
        }

        return $this;
    }

    public function removeDeck(deck $deck): self
    {
        $this->decks->removeElement($deck);

        return $this;
    }

    public function __toString() {
        return $this->question;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 */
class User implements UserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private $password;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity=Deck::class, mappedBy="author")
     */
    private $decks;

    /**
     * @ORM\OneToMany(targetEntity=Card::class, mappedBy="author")
     */
    private $cards;

    /**
     * @ORM\ManyToMany(targetEntity=Deck::class, inversedBy="fans")
     * @ORM\JoinTable(name="favorites_fans")
     */
    private $favorites;

    /**
     * @ORM\ManyToOne(targetEntity=Language::class, inversedBy="users")
     * @ORM\JoinColumn(nullable=false)
     */
    private $language_native;

    /**
     * @ORM\ManyToOne(targetEntity=Language::class)
     * @ORM\JoinColumn(nullable=false)
     */
    private $language_learn;


    public function __construct()
    {
        $this->decks = new ArrayCollection();
        $this->cards = new ArrayCollection();
        $this->favorites = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }

    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getPassword(): string
    {
        return (string) $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function getSalt()
    {
        // not needed when using the "bcrypt" algorithm in security.yaml
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }


    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|deck[]
     */
    public function getDecks(): Collection
    {
        return $this->decks;
    }

    public function addDecks(deck $deck): self
    {
        if (!$this->decks->contains($deck)) {
            $this->decks[] = $deck;
            $deck->setAuthor($this);
        }

        return $this;
    }

    public function removeDecks(deck $deck): self
    {
        if ($this->decks->removeElement($deck)) {
            // set the owning side to null (unless already changed)
            if ($deck->getAuthor() === $this) {
                $deck->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|card[]
     */
    public function getCards(): Collection
    {
        return $this->cards;
    }

    public function addCards(card $card): self
    {
        if (!$this->cards->contains($card)) {
            $this->card[] = $card;
            $card->setAuthor($this);
        }

        return $this;
    }

    public function removeCards(card $card): self
    {
        if ($this->cards->removeElement($card)) {
            // set the owning side to null (unless already changed)
            if ($card->getAuthor() === $this) {
                $card->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|deck[]
     */
    public function getFavorites(): Collection
    {
        return $this->favorites;
    }

    public function addFavorite(deck $favorite): self
    {
        if (!$this->favorites->contains($favorite)) {
            $this->favorites[] = $favorite;
        }

        return $this;
    }

    public function removeFavorite(deck $favorite): self
    {
        $this->favorites->removeElement($favorite);

        return $this;
    }

    public function getLanguageNative(): ?language
    {
        return $this->language_native;
    }

    public function setLanguageNative(?language $language_native): self
    {
        $this->language_native = $language_native;

        return $this;
    }

    public function getLanguageLearn(): ?language
    {
        return $this->language_learn;
    }

    public function setLanguageLearn(?language $language_learn): self
    {
        $this->language_learn = $language_learn;

        return $this;
    }

}

templates/pages/administration/dashboard.html.twig
{% extends './pages/administration/admin.base.html.twig'%}
{% block title %}Dashboard administrateur{% endblock %}
{% block body %}

<div class="content">
  <div class="container-fluid">
    <div class="card">
      <div class="card-header card-header-primary">
        <h4 class="card-title">Derniers messages reçus</h4>
        <p class="card-category text-white">
          {% set count = 0 %} {% for message in allMessages %} {% set
            count = count + 1 %} {% endfor %}
          {% if count == 0 %}
          Vous n'avez aucun message
          {% else %}
          <a href="{{ path('admin-messages') }}" class=" text-white">Voir tous les messages 
              (total : {{ count }})
            </a>
          {% endif %}
        </p>
      </div>
      <div class="card-body table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th class="text-primary">ID</th>
              <th class="text-primary">Expéditeur</th>
              <th class="text-primary">Email</th>
              <th class="text-primary">Sujet</th>
              <th class="text-primary">Contenu</th>
              <th class="text-primary">Reçu le</th>
            </tr>
          </thead>
          <tbody>
            {% for message in messages %}
            <tr>
              <td>{{ message.id }}</td>
              <td>{{ message.sender }}</td>
              <td>{{ message.email }}</td>
              <td>{{ message.subject }}</td>
              <td>{{ message.content }}</td>
              <td>{{message.createdAt | date("d/m/Y") }}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4 col-md-12">
        <div class="card">
          <div class="card-header card-header-primary">
            <h4 class="card-title">Derniers inscrits</h4>
            <p class="card-category text-white">
              {% set count = 0 %} {% for user in allUsers %} {% set
                count = count + 1 %} {% endfor %}
              {% if count == 0 %}
              Il n'y a aucun inscrit
              {% else %}
              <a href="{{ path('admin-users') }}" class=" text-white">Voir tous les inscrits 
                  (total : {{ count }})
                </a>
              {% endif %}
            </p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th class="text-primary">ID</th>
                  <th class="text-primary">Nom</th>
                  <th class="text-primary">Langue mat.</th>
                  <th class="text-primary">Apprend le</th>
                  <th class="text-primary">Inscrit depuis</th>
                  <th class="text-primary">Cartes créées</th>
                  <th class="text-primary">Decks crées</th>
                </tr>
              </thead>
              <tbody>
                {% for user in users %}
                <tr>
                  <td>{{ user.id }}</td>
                  <td>
                    <a href="{{ path('admin-user', { id: user.id }) }}">{{ user.name }}</a>
                  </td>
                  <td>
                    <a href="{{ path('language-details', { id: user.languageNative.id }) }}">{{ user.languageNative.name }}</a>
                  </td>
                  <td>
                    <a href="{{ path('language-details', { id: user.languageLearn.id }) }}">{{ user.languageLearn.name }}</a>
                  </td>
                  <td>{{user.createdAt | date("d/m/Y") }}</td>
                  <td class="text-center">
                    {% set count = 0 %} {% for card in user.cards %} {% set
                    count = count + 1 %} {% endfor %}
                    {{ count }}
                  </td>
                  <td class="text-center">
                    {% set count = 0 %} {% for deck in user.decks %} {% set
                    count = count + 1 %} {% endfor %}
                    {{ count }}
                  </td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-12">
        <div class="card">
          <div class="card-header card-header-info">
            <h4 class="card-title">Dernières cartes</h4>
            <p class="card-category text-white">
              {% set count = 0 %} {% for card in allCards %} {% set
                count = count + 1 %} {% endfor %}
              {% if count == 0 %}
              Il n'y a aucune carte
              {% else %}
              <a href="{{ path('admin-cards') }}" class=" text-white">Voir toutes les cartes 
                  (total : {{ count }})
                </a>
              {% endif %}
            </p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th class="text-info">ID</th>
                  <th class="text-info">Langue</th>
                  <th class="text-info">Catégorie</th>
                  <th class="text-info">Créé le</th>
                  <th class="text-info">Auteur</th>
                </tr>
              </thead>
              <tbody>
                {% for card in cards %}
                <tr>
                  <td>
                    <a href="{{ path('admin-card', { id: card.id }) }}">{{ card.id }}</a>
                  </td>
                  <td><a href="{{ path('language-details', { id: card.author.languageLearn.id }) }}">{{ card.author.languageLearn.name }}</td></a>
                  <td><a href="{{ path('category-details', { id: card.category.id }) }}">{{ card.category.name }}</a></td>
                  <td>{{card.createdAt | date("d/m/Y") }}</td>
                  <td><a href="{{ path('admin-user', { id: card.author.id }) }}">{{ card.author.name }}</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <div class="col-lg-4 col-md-12">
        <div class="card">
          <div class="card-header card-header-warning">
            <h4 class="card-title">Derniers decks</h4>
            <p class="card-category text-white">
              {% set count = 0 %} {% for deck in allDecks %} {% set
                count = count + 1 %} {% endfor %}
              {% if count == 0 %}
              Il n'y a aucun deck
              {% else %}
              <a href="{{ path('admin-decks') }}" class=" text-white">Voir tous les decks 
                  (total : {{ count }})
                </a>
              {% endif %}
            </p>
          </div>
          <div class="card-body table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th class="text-warning">ID</th>
                  <th class="text-warning">Nom</th>
                  <th class="text-warning">Langue</th>
                  <th class="text-warning">Créé le</th>
                  <th class="text-warning">Auteur</th>
                </tr>
              </thead>
              <tbody>
                {% for deck in decks %}
                <tr>
                  <td>{{ deck.id }}</td>
                  <td>
                    <a href="{{ path('admin-deck', { id: deck.id }) }}">{{ deck.name }}</a>
                  </td>
                  <td><a href="{{ path('language-details', { id: deck.author.languageLearn.id }) }}">{{ deck.author.languageLearn.name }}</a></td>
                  <td>{{ deck.createdAt | date("d/m/Y") }}</td>
                  <td><a href="{{ path('admin-user', { id: deck.author.id }) }}">{{ deck.author.name }}</a></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>



{% endblock body %}

templates/pages/administration/user.html.twig
{% extends './pages/administration/admin.base.html.twig'%}
{% block title %}Détails d'un utilisateur{% endblock %}
{% block body%}

<div class="content">
  <div class="container-fluid">
    <div class="row">

      <div class="col-lg-4 col-md-4">
        <div class="card">
          <div class="card-header card-header-info card-header-icon">
            <div class="card-icon">
              {% if user.image is not null%}
              <p style="width:80% ; height:80%" class="m-0 p-0">
              <img
                src="/uploads/images/{{ user.image }}"
                class="img avatar rounded"
                width="80px"
                height="auto"
              /></p>
              {% else %}
              <p style="width:80% ; height:80%" class="m-0 p-0">
              <img
                src="/uploads/images/default-user.png"
                class="img avatar rounded"
                width="80px"
                height="auto"
              /></p>
              {% endif %}
            </div>
            <p class="h3 card-title text-right">Nom : {{ user.name }}</p>
            <p class="card-category text-right"> {% if user.roles[0] == 'ROLE_ADMIN' %} Administrateur {%
              elseif user.roles[0] == 'ROLE_USER' %} Utilisateur {%
              endif %}</p>
          </div>
          <div class="card-footer">
            <div class="stats">
              <i class="material-icons text-info">supervised_user_circle</i>
              <a href="{{ path('admin-users') }}" class="info-link"
                >Retour à la liste</a
              >
            </div>
          </div>
          <div class="card-body">
            <div class="tab-content table-responsive">
              <div class="m-3">
                <table class="table">
                  <thead>
                    <tr>
                      <th>ID</th>
                      <th>Auteur</th>
                      <th>Email</th>
                      <th>Inscrit le</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>{{ user.id }}</td>
                      <td>{{ user.name}}</td>
                      <td>{{ user.email }}</td>
                      <td>{{user.createdAt | date("d/m/Y") }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div class="tab-content table-responsive">
              <div class="m-3">
                <table class="table text-left">
                  <thead>
                    <tr>
                      <th>Parle</th>
                      <th>Apprend</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td><a href="{{ path('language-details', { id: user.languageNative.id }) }}">{{ user.languageNative.name}}</a></td>
                      <td><a href="{{ path('language-details', { id: user.languageLearn.id }) }}">{{ user.languageLearn.name}}</a></td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>

            <div class="text-center">
                <form
                method="POST"
                action="{{ path('admin-user-delete', { id: user.id }) }}"
                onsubmit="return confirm('Supprimer cet utilisateur ? Cette action est définitive !')"
              >
                <button class="btn btn-danger btn-round">supprimer</button>
              </form>
            </div>

          </div>

        </div>
      </div>
  

      <div class="col-lg-8 col-md-8">

        <div class="card">

          <div class="card-header card-header-tabs card-header-info">
            <div class="nav-tabs-navigation">
              <div class="nav-tabs-wrapper">
                <ul class="nav nav-tabs" data-tabs="tabs" role="tablist">
                  <li class="nav-item">
                    <a class="nav-link" href="#cards" data-toggle="tab" role="tab">
                      <i class="material-icons">bookmark</i>
                      {% set count = 0 %} {% for card in user.cards %} {% set count =
                        count + 1 %} {% endfor %}
                      {{count }} carte(s)
                      <div class="ripple-container"></div>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#decks" data-toggle="tab" role="tab">
                      <i class="material-icons">bookmarks</i>
                      {% set count = 0 %} {% for deck in user.decks %} {% set count =
                        count + 1 %} {% endfor %}
                      {{count }} deck(s)
                      <div class="ripple-container"></div>
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#favorites" data-toggle="tab">
                      <i class="material-icons">favorite</i>
                      {% set count = 0 %} {% for favorite in user.favorites %} {% set count =
                        count + 1 %} {% endfor %}
                      {{count }} favori(s)
                      <div class="ripple-container"></div>
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>

          <div class="card-body">
            <div class="tab-content table-responsive">

              <div class="tab-pane active" id="cards"  role="tabpanel">
                <p class="h3">
                {% set count = 0 %} {% for card in usersCards %} {% set count =
                count + 1 %} {% endfor %} 
                {% if count == 0 %}
                <p class="text-info">Pas encore de carte.</p>
                {% else %}
                {{ count }} carte(s) créée(s) :
                </p>
                <table class="table" id="usertable">
                  <thead>
                    <tr>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('usertable', 0)">ID<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('usertable', 1)">Catégorie<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('usertable', 2)">Créée le<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info">Voir</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for card in cards%}
                    <tr>
                      <td>{{ card.id }}</td>
                      <td><a href="{{ path('category-details', { id: card.category.id }) }}"
                        >{{ card.category.name }}</td>
                      <td>{{card.createdAt | date("d/m/Y") }}</td>
                      <td class="td-actions">
                        <a href="{{ path('admin-card', { id: card.id }) }}"
                          ><button
                            type="button"
                            rel="tooltip"
                            title=""
                            class="btn btn-white btn-link btn-sm"
                          >
                            <i class="material-icons">remove_red_eye</i>
                          </button></a
                        >
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                {% endif %}
                {{ knp_pagination_render(cards) }}
              </div>


              <div class="tab-pane" id="decks" role="tabpanel">
                <p class="h3">
                  {% set count = 0 %} {% for deck in usersDecks %} {% set count =
                  count + 1 %} {% endfor %} 
                  {% if count == 0 %}
                  <p class="text-info">Pas encore de deck.</p>
                  {% else %}
                  {{ count }} deck(s) créé(s) :
                </p>
    
                <table class="table" id="decktable">
                  <thead>
                    <tr>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('decktable', 0)">ID<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('decktable', 1)">Nom<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('decktable', 2)">Créé le<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info">Voir</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for deck in decks%}
    
                    <tr>
                      <td>{{ deck.id }}</td>
                      <td>{{ deck.name }}</td>
                      <td>{{deck.createdAt | date("d/m/Y") }}</td>
                      <td class="td-actions">
                        <a href="{{ path('admin-deck', { id: deck.id }) }}"
                          ><button
                            type="button"
                            rel="tooltip"
                            title=""
                            class="btn btn-white btn-link btn-sm"
                          >
                            <i class="material-icons">remove_red_eye</i>
                          </button></a
                        >
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                {% endif %}

              </div>

              <div class="tab-pane" id="favorites">
                <p class="h3">
                  {% set count = 0 %} {% for favorite in user.favorites %} {% set count =
                  count + 1 %} {% endfor %} 
                  {% if count == 0 %}
                  <p class="text-info">Pas encore de favori.</p>
                  {% else %}
                  {{ count }} favori(s) :
                </p>
    
                <table class="table" id="favtable">
                  <thead>
                    <tr>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('favtable', 0)">ID<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('favtable', 1)">Auteur<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('favtable', 2)">Nom<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info" style="cursor: pointer" onclick="sortTable('favtable', 3)">Créé le<i class="material-icons icon">keyboard_arrow_up</i></th>
                      <th class="text-info">Voir</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for favorite in user.favorites%}
    
                    <tr>
                      <td>{{ favorite.id }}</td>
                      <td><a href="{{ path('admin-user', { id: favorite.author.id }) }}">{{ favorite.author.name }}</a></td>
                      <td><a href="{{ path('admin-deck', { id: favorite.id }) }}"
                        >{{ favorite.name }}</a></td>
                      <td>{{favorite.createdAt | date("d/m/Y") }}</td>
                      <td class="td-actions">
                        <a href="{{ path('admin-deck', { id: favorite.id }) }}"
                          ><button
                            type="button"
                            rel="tooltip"
                            title=""
                            class="btn btn-white btn-link btn-sm"
                          >
                            <i class="material-icons">remove_red_eye</i>
                          </button></a
                        >
                      </td>
                    </tr>
                    {% endfor %}
                  </tbody>
                </table>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>


{% endblock body%}